source 'https://rubygems.org'
ruby '2.3.3'


gem 'rails', '~> 5.1.0'
gem 'sass-rails', '~> 5.0'
gem 'bootstrap-sass'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'turbolinks', '~> 5'
gem 'devise', '~> 4.2'
gem 'puma', '~> 3.7'
gem 'jbuilder', '~> 2.5'
gem 'tzinfo-data'
gem 'bcrypt', '~> 3.1.11'
gem 'sqlite3'
